* How did I get to Emacs?
I assume that you're motivated to use Emacs. If you're not, you should. [[https://www.youtube.com/watch?v=EsAkPl3On3E][Convince
yourself]].

I started using Emacs on July, 2018. I completed two bachelor's degrees from the
University of Porto between 2011 and 2017. I started a master's program on pure maths
but I quitted after the first semester. With that being said, I'm just a regular
Joe Doe. Before July 2018 I didn't know GNU/Linux at all - no basic bash
commands, no vi, no nothing. My background was paper, pencils, chalk and
blackboards.

How did the shift happen? Well, I had a friend who was using Ubuntu. Besides,
once I met a professor in his office and he was using a "strange program". I
asked about it, he replied - "It's Emacs! I write all my \LaTeX papers here,
answer e-mails and program in here!". That seemed just unreal. At that time, I
was also starting to shift from paper to a computer. I stopped taking notes on
paper in lectures. I using Lyx to write \LaTeX docs, and I thought it couldn't
get better than that since I was looking at my collegues typing \LaTeX from
scratch and I felt sorry for them.

At that time I only scrathed the surface of the folling idea: "Being able to
type acuratelly and fast on a computer is convenient". What I didn't know
is that my life would soon be so deeply based on text.

* Where to start?
I recommend running Emacs on a GUI. This guy agrees and he [[https://blog.aaronbieber.com/2016/12/29/don-t-use-terminal-emacs.html][expands]] on that.

Well, like anyone will advice you, please read the tutorial.

* How do I carry my org files?
I have a smartphone, one of those Android. I mitigated the Google influence by
not adding a Google account or not running Google apps. Anyway, I'm sure I'm
running endless malware in it. I'd like to get one of [[https://puri.sm/products/librem-5/][these]], oneday.

So, my "Appstore" is [[https://f-droid.org/][F-Droid]]. In there you'll find [[https://termux.com/][Termux]]. That coupled with
[[https://nextcloud.com/][Nextcloud]] makes it possible me to access my org files and agenda anywhere,
anytime and to sync effortlessly. My life in text.

* Sidenote on GNU
Emacs is all about freedom. When you work in it, you feel it was designed by
people who want the same you want - something reliable without bullshit.

It is quite helpful if you get acquainted with [[https://en.wikipedia.org/wiki/GNU_Project][GNU]], [[https://en.wikipedia.org/wiki/Free_Software_Foundation][Free Software Foundation
(FSF)]] and [[https://www.youtube.com/watch?v=jUibaPTXSHk][Richard Stallman]]. I wish universities talked more Richard Stallman,
and less Linus Torvalds (no to be discredited). I wish they didn't teach
students any proprietary software. Free thought, free world.

The road to freedom is hard. I do find myself doing thing that don't respect the
FSF. But at least I'm conciously and proactively fighting years of bad education.
