#+TITLE: .emacs.d config readme
#+STARTUP: latexpreview
#+OPTIONS: toc:nil num:nil email:t

* How did I get to Emacs?
** Who am I?
I assume that you're motivated to use Emacs. If you're not - [[https://www.youtube.com/watch?v=EsAkPl3On3E][convince yourself]].

I started using Emacs inn August, 2018. I completed two bachelor's degrees from
the University of Porto between 2011 and 2017. I started a master's program on
pure maths, but quitted after the first semester and started to work for
[[https://en.wikipedia.org/wiki/Vestas][Vestas]]. With that being said, I'm just a guy and I think that Emacs is not as
difficult as people usually tell. Back then, I barely knew what GNU/Linux was at
all. I knew that something called command line existed, but I thought it was
just for hackers. My background was paper, pencils, chalk and blackboards.

** How did the shift happen?
Well, I had a friend who was using Ubuntu. Besides, once I met a [[https://cmup.fc.up.pt/cmup/jalmeida/][professor]] in
his office, and he was using a "strange program". I asked about it, he replied -
"It's Emacs! I write all my \LaTeX papers here, answer e-mails and program in
here!". That seemed quite unreal. At that time, I was also starting to shift from
paper to computers. I stopped taking notes on paper in lectures to start using [[https://en.wikipedia.org/wiki/Lyx][Lyx]] to
write \LaTeX docs. I thought it couldn't get better than that, since I was
looking at my collegues typing \LaTeX from scratch and I felt sorry for them.

At that time I only scratched the surface of the folling idea: "Being able to
type acuratelly and fast on a computer is convenient". What I didn't know
is that my life would soon be so deeply based on text - [[https://www.youtube.com/watch?v=SzA2YODtgK4][org mode]] is another universe.

* Where to start?
I recommend running Emacs on a GUI. This guy agrees and [[https://blog.aaronbieber.com/2016/12/29/don-t-use-terminal-emacs.html][expands]] on that.

Well, like anyone will advice you, please read the tutorial.

* Evolution
I started working on my own init.el roughly on December, 2018.

Following the trend, I went for a literate programming kind of approach coupled
with [[https://duckduckgo.com/l/?kh=-1&uddg=https%253A%252F%252Fgithub.com%252Fjwiegley%252Fuse%252Dpackage][use-package]].

* How do I carry my org files?
I have a smartphone, one of those Android. I mitigated the Google influence by
not adding a Google account or not running Google apps. Anyway, I'm sure I'm
running endless malware in it. I'd like to get one of [[https://puri.sm/products/librem-5/][these]], oneday.

So, my "Appstore" is [[https://f-droid.org/][F-Droid]]. In there you'll find [[https://termux.com/][Termux]]. That coupled with
[[https://nextcloud.com/][Nextcloud]] makes it possible me to access my org files and agenda anywhere,
anytime and to sync effortlessly. My life in plain text.

** Tutorial[fn:1]
- [[https://f-droid.org/packages/com.termux/][Install Termux]]
- Install Nextcloud (available on F-Droid)
- Download the needed .org files from Nextcloud to your device
- Run the following commands
  - pkg install emacs, git
  - [[https://wiki.termux.com/wiki/Sharing_Data][termux-setup-storage]] (to create symlinks)
- A symlink might be needed depending on the way you set org-agenda-files and on
  where the Nextcloud are located

* Sidenote on GNU
Emacs is all about freedom. When you work in it, you feel it was designed by
people who want the same you want - something reliable without bullshit.

It is quite helpful if you get acquainted with [[https://en.wikipedia.org/wiki/GNU_Project][GNU]], [[https://en.wikipedia.org/wiki/Free_Software_Foundation][Free Software Foundation
(FSF)]] and [[https://www.youtube.com/watch?v=jUibaPTXSHk][Richard Stallman]]. I wish universities talked more Richard Stallman,
and less Linus Torvalds (not to his discredit). I wish they didn't teach
students any proprietary software. I wish engineers had morals.

The road to freedom is hard. I do find myself doing thing that don't respect the
FSF. But at least I'm conciously and proactively fighting years of bad
education.

*Free thought, free world.*

* Footnotes

[fn:1] Write me if something doesn't work for you.
