#+TITLE: Overview
#+AUTHOR: André Alexandre Gomes
#+EMAIL: andremegafone@gmail.com

| OS             | [[https://guix.gnu.org/][GNU/Linux Guix]]   |
| Text Editor    | [[https://www.gnu.org/software/emacs/][GNU Emacs 27.1]]   |
| Window manager | [[https://swaywm.org/][sway ]]& [[https://www.gnome.org/][GNOME]]     |
| Web Browser    | [[https://www.gnu.org/software/emacs/manual/html_node/eww/][eww]] & [[https://www.gnu.org/software/gnuzilla/][GNU icecat]] |
| Shell          | [[https://www.gnu.org/software/emacs/manual/html_mono/eshell.html][eshell]]           |
| Media Player   | [[https://www.gnu.org/software/emms/][emms]]             |
| Mail/News      | [[http://www.gnus.org/][gnus]]             |
#+TBLFM: @2$2='(substring (emacs-version) 0 15)
# (org-table-recalculate-buffer-tables)

* Motivation
Free software grants users the 4 freedoms to run, study, redistribute
and improve programs.  As a result, these programs are usually
extensible and flexible and those configurations can be saved as text
files.  They're usually hidden files, thus prepended by a dot, hence the
set of these files is usually called *dotfiles*.  Users want to keep
them so that their computing environment is easily reproducible on a new
machine.  That's the scope of this project.

* My personal revolution
I assume you're motivated to use Emacs.  If you're not, let [[https://www.youtube.com/watch?v=EsAkPl3On3E][Protesilaos
Stravrou convince you]].

** Who am I?
An idiot who:
- completed two bachelor's degrees in Physics and Mathematics (University of
  Porto, 2011-2017);
- started a master's on Pure Maths (2017), but quitted after the first semester;
- started to work for [[https://en.wikipedia.org/wiki/Vestas][Vestas]] and using Emacs in August 2018.

Back then, I barely knew what GNU/Linux was at all.  My background was
theoretical so a piece a paper and a pen were my tools.

The point is: if Emacs is your cup of tea, you shall not struggle at all.  I
still don't get those who tell that the learning curve is steep.  Isn't the
profit curve even steeper?  It's a matter of attitude and self motivation.  I have
fun with Emacs everyday.

If you have never suffered while learning, I wonder if you have ever learnt
anything.  The process starts with the traumatic experience of helplessness
towards new faculties that are yet to be acquired.

** The transition
I knew Ubuntu existed from a friend, but he was being driven by the convenience
of it.  At that time, I didn't know free software, Richard Stallman or
GNU/Linux.  It was when I stepped closer to these ethical issues that it
triggered my curiosity.

Once, while meeting a [[https://cmup.fc.up.pt/cmup/jalmeida/][professor]] in his office, I saw It for the first time.  I
asked about It.

"It's Emacs!  I write my \LaTeX papers, answer e-mails and write my programs
without ever leaving it!".

That seemed quite impressive, and I kept it in the back of my head.  I was also
shifting from paper to computers.  For instance, I took lecture notes using
[[https://en.wikipedia.org/wiki/Lyx][Lyx]] to generate \LaTeX docs.  That was already quite impressive, since I
was making use of keybindings and other "wizardry" to suppress the repetitiveness
of certain things.

I scratched the surface of: "Being able to type accurately and fast on a
computer is convenient".  What I didn't know is that my life would soon be so
deeply based on text, and the way [[https://www.youtube.com/watch?v=SzA2YODtgK4][org mode]] changes life.

* Where to start?
I recommend running Emacs on a GUI.  He agrees and [[https://blog.aaronbieber.com/2016/12/29/don-t-use-terminal-emacs.html][expands]] on that.

Run it on GNU/Linux for obvious reasons.  If circumstances make it impossible,
then run it on a virtual machine.  He [[https://youtu.be/RDrG-_kapaQ][expands]] on that.

Emacs greets you!

/Welcome to GNU Emacs, one component of the GNU/Linux operating system./

Get acquainted with what GNU stands for and read the tutorial (you might need to
read it more than once).

* Evolution
** Customization
I started working on my own init.el on [2018-12-10].

Following the trend, I went for literate programming coupled with
[[https://duckduckgo.com/l/?kh=-1&uddg=https%253A%252F%252Fgithub.com%252Fjwiegley%252Fuse%252Dpackage][use-package]].

Vanilla Emacs (not customized) doesn't suck and you should learn it
well.  The community is amazing and provides amazing packages.  Try them out if
your needs require.

** Org agenda
Can't live without it.  Words can't express the joy.

** E-mail
Use gnus and you'll get a news reader as a bonus.

** Eww as a browser
The built-in Emacs browser, eww, will not always replace a browser.  Mainly,
because it doesn't run Javascript.  But you can use it for most of the things you
need, with the added benefit that you won't leave your text editor.

** Studying Emacs
Emacs is the self-documenting text editor, so C-h i has everything you need!

** Emacs Lisp
If you love Emacs, you'll start learning it before you notice.

* Carrying org files
I have a smartphone, one of those Android.  I mitigated Google's influence by not
adding a Google account or by not running Google apps.  Anyway, I'm sure I'm
running endless malware in it anyway.

So, my "App-store" is [[https://f-droid.org/][F-Droid]].  In there you'll find [[https://termux.com/][Termux]].  That coupled with
[[https://nextcloud.com/][Nextcloud]] makes it possible me to access my org files and agenda anywhere,
anytime and to sync effortlessly.  My life in plain text.

I started using LineageOS on [2020-02-25].

** Tutorial
- [[https://f-droid.org/packages/com.termux/][Install Termux]]
- Install Nextcloud (available on F-Droid)
- Download the needed .org files from Nextcloud to your device
- Run the following commands
  - pkg install emacs, git
  - [[https://wiki.termux.com/wiki/Sharing_Data][termux-setup-storage]] (to create symlinks)
- A symlink might be needed depending on the way you set org-agenda-files and on
  where the Nextcloud files are located

[[https://linuxconfig.org/ssh-into-linux-your-computer-from-android-with-termux][ssh]]

* OS
There's only one operating system worth using - GNU/Linux.  It comes in many
shapes and flavours, people call them distributions (distros).  [[https://www.gnu.org/distros/free-distros.en.html][Only a small
minority is endorsed by the FSF]].  Beginners should consider using PureOS.  On the
non-free side, consider Ubuntu.  More advanced users might be interested in GNU
Guix (or NixOS, the non-free counterpart).  Guix and Nix can also be used as
package managers.

GNU Guix supports a declarative system configuration, which suits the aim of
this project.

Packages from Nix might be used if the package isn't available in Guix.  Users
should consider defining their our packages if they're missing.

* Window Managers and Desktop Environments
After some considerations regarding package managers of distros, one of the things
that distinctively changes the user's productivity is the way he manages
windows.

There are full-blown desktop environments like GNOME that take lots of
resources.  Although they're user-friendly, tilling window managers (think how
Emacs handles windows) are more interesting options.

# I shall be using StumpWM since it claims to be "The Emacs of window managers".
# Indeed, the keybindings resemble Emacs and it is implemented in Common Lisp.

* Sidenote on GNU
GNU Emacs is all about freedom.  When you work in it, you feel it was designed by
people who want the same you want - reliable tools, no bullshit added.

It is quite helpful if you get acquainted with [[https://en.wikipedia.org/wiki/GNU_Project][GNU]], [[https://en.wikipedia.org/wiki/Free_Software_Foundation][Free Software Foundation
(FSF)]] and [[https://www.youtube.com/watch?v=jUibaPTXSHk][Richard Stallman]].

I wish the world talked Richard Stallman and Linus Torvalds in a balanced
proportion.

I wish students weren't being taught proprietary software.

I wish companies had ethics.

The road to freedom is hard.  I'm consciously and proactively fighting years of
bad education.

*Free Thought, Free World.*

#+begin_quote
Arguing that you don't care about the right to privacy because you have nothing
to hide is no different from saying you don't care about free speech because you
have nothing to say. (Edward Snowden)
#+end_quote

* Hardware
- [[https://www.waveshare.com/eink-disp-103.htm?sku=17660][eink]]

* dotfiles I follow
- [[https://github.com/daviwil/dotfiles][David Wilson]]
- [[https://git.sr.ht/~w96k/dotfiles][Mikhail Kirillov]]
- [[https://github.com/oantolin/emacs-config][Omar Antolín Camarena]]
- [[https://gitlab.com/ambrevar/dotfiles][Pierre Neidhardt]]
- [[https://gitlab.com/protesilaos/dotfiles][Protesilaos Stravrou]]
