#+TITLE: dotfiles planning

- State "TODO"       from              [2019-07-22 Mon]

* TODO
- mv gitconfig to .config
- emacsdaemon?
- change dict according to selected input method
- [[https://blog.aaronbieber.com/2015/08/04/authoring-emacs-packages.html][Create package with portuguese holidays]]
- add personal holidays in a private file
- Syncthing vs Nextcloud vs cron?
- [[https://medium.com/@sserialdev/emacs-in-the-container-age-5c0c222cfee][Emacs inside a docker container?]]
- use-package and guix regarding emacs pkgs
- write pkg def for missing emacs pkgs with guix
- add emacs-counsel
- update emacs-zenburn-theme
- git config file (~/.gitconfig or ~/.config/git/config file)

* OS
There's only one operating system worth using - GNU/Linux. It comes in many
shapes and flavours, people call them distributions (distros). [[https://www.gnu.org/distros/free-distros.en.html][Only a small
minority is endorsed by the FSF]]. Beginners should consider using PureOS. On the
non-free side, consider Ubuntu. More advanced users might be interested in
GuixSD (or NixOS, the non-free counterpart). Guix and Nix can also be used as
package managers.

GuixSD supports a declarative system configuration, which suits the aim of this
project.

Packages from Nix might be used if the package isn't available in Guix. Users
should consider defining their our packages if they're missing.

* Window Managers and Desktop Environments
After some considerations regarding package managers of distros, one of the things
that distinctively changes the user's productivity is the way he manages
windows.

There are full-blown desktop environments like GNOME that take lots of
resources. Although they're user-friendly, tilling window managers (think how
Emacs handles buffers) are more interesting options.

I shall be using StumpWM since it claims to be "The Emacs of window
managers". Indeed, the keybindings resemble Emacs and it is implemented in
Common Lisp.

** TODO stumpwm contrib git submodule
- State "TODO"       from              [2020-02-05 Wed 13:46]

* Appearance
- transparent Emacs and desktop image
- top bar with watch

gsettings set org.gnome.desktop.background picture-path


compton (transparency)
nitrogen (wallpeper)

* Keyboard
Check base.lst for documention.

- US and RU layouts
- S-<SPC> to change layout
- Capslock LED shows that RU layout is active
- Compose key on left ctrl
- Capslock as ctrl

* Sync org files
#+begin_src bash
  owncloudcmd -s -u user -p pw $HOME/NextCloud/ https://cloud.owncube.com/remote.php/webdav/
#+end_src

[[https://github.com/owncloud/client/issues/2002#issuecomment-98747743][cron script for owncloud]]

* Email
[[https://www.fsf.org/resources/webmail-systems][fsf advice]]

[[https://www.emacswiki.org/emacs/GnusGmail][gnus tutorial]]

setup posteo email

webmail fcup?

aagomes@protonmail.com
aagomes@pm.com

disroot

[[https://github.com/kensanata/ggg#gmail-gnus-gpg-guide-gggg][how to encrypt]]

* Wifi manager
nmtui

https://aur.archlinux.org/bcm4350-firmware.git
nix-env -iA nixos.b43Firmware_6_30_163_46

* Brightness
how to persistently change permissions of a file.
