#+TITLE: dotfiles planning

- State "TODO"       from              [2019-07-22 Mon]

* TODO
guix package --list-installed
nix-env -q

[[https://ambrevar.xyz/guix-advance/][more on guix]]

* OS
There's only one operating system worth using - GNU/Linux. It comes in many
shapes and flavours, people call them distributions (distros). [[https://www.gnu.org/distros/free-distros.en.html][Only a small
minority is endorsed by the FSF]]. Beginners should consider using PureOS. On the
non-free side, consider Ubuntu. More advanced users might be interested in
GuixSD (or NixOS, the non-free counterpart). Guix and Nix can also be used as
package managers.

GuixSD supports a declarative system configuration, which suits the aim of this
project.

Packages from Nix might be used if the package isn't available in Guix. Users
should consider defining their our packages if they're missing.

* Window Managers and Desktop Environments
After some considerations regarding package managers of distros, one of the things
that distinctively changes the user's productivity is the way he manages
windows.

There are full-blown desktop environments like GNOME that take lots of
resources. Although they're user-friendly, tilling window managers (think how
Emacs handles buffers) are more interesting options.

I shall be using StumpWM since it claims to be "The Emacs of window
managers". Indeed, the keybindings resemble Emacs and it is implemented in
Common Lisp.

* Browser
Eww as a text-based browser.
Icecat if I need to run JS.

Extensions:
- dark reader
- saka key

The next browser also looks interesting. Worth having a look.

* Programming languages
- Python
- Haskell
- Go
- \LaTeX

* Appearance
- transparent Emacs and desktop image
- top bar with watch

gsettings set org.gnome.desktop.background picture-path

* Keyboard
Check base.lst for documention.

- US and RU layouts
- S-<SPC> to change layout
- Capslock LED shows that RU layout is active
- Compose key on left ctrl
- Capslock as ctrl

* Sync org files
#+begin_src bash
  owncloudcmd -s -u user -p pw $HOME/NextCloud/ https://cloud.owncube.com/remote.php/webdav/
#+end_src

[[https://github.com/owncloud/client/issues/2002#issuecomment-98747743][cron script for owncloud]]

* Telegram
telega for emacs?

* ssh keys?

* Email
[[https://www.fsf.org/resources/webmail-systems][fsf advice]]

[[https://www.emacswiki.org/emacs/GnusGmail][gnus tutorial]]

i68scb+18z6fep0c@sharklasers.com
aadcg@sharklasers.com

setup posteo email

webmail fcup?

aagomes@protonmail.com
aagomes@pm.com

disroot

* Wifi manager
nmtui

https://aur.archlinux.org/bcm4350-firmware.git
nix-env -iA nixos.b43Firmware_6_30_163_46

* Dictionary
aspell

* Brightness
xrandr -s 2560x1440
xrandr --output <screen> --brightness 0.x / 1

Screen appears to be less bright while using StumpWM.
