#+TITLE: dotfiles planning

- State "TODO"       from              [2019-07-22 Mon]

* TODO
guix package --list-installed
nix-env -q

[[https://ambrevar.xyz/guix-advance/][more on guix]]

* OS
There's only one operating system worth using - GNU/Linux. It comes in many
shapes and flavours, people call them distributions (distros). [[https://www.gnu.org/distros/free-distros.en.html][Only a small
minority is endorsed by the FSF]]. Beginners should consider using PureOS. On the
non-free side, consider Ubuntu. More advanced users might be interested in
GuixSD (or NixOS, the non-free counterpart). Guix and Nix can also be used a
package managers.

GuixSD supports a declarative system configuration, which suits the aim of this
project.

Packages from Nix might be used if the package isn't available in Guix. Users
should consider define their our packages when they're missing.

* Window Managers and Desktop Environments
After some considerations regarding package managers of distros, one of the things
that distinctively changes the user's productivity is the way he manages
windows.

There are full-blown desktop environments like GNOME that take lots of
RAM. Although they're beginner friendly, tilling window managers (think how
Emacs handles buffers) are more interesting options.

I shall be using StumpWM since I can configure it in Common Lisp.

Requires stumpwm contrib [[https://github.com/stumpwm/stumpwm-contrib.git][repo]]. Clone inside .stumpwm.d.

[[https://github.com/sdilts/mahogany][This]] looks cool.

- C-t breaks C-x C-t
root key on super key?

* Browser
Eww as a text-based browser.
Icecat for the rest. (Firefox based)

Extensions:
- dark reader
- saka key

The next browser also looks interesting.

* TODO Programming languages
- State "TODO"       from              [2019-11-17 Sun 14:04]

- Python
- Haskell
- Go
- \LaTeX

* Appearance
- transparent Emacs and desktop image
- top bar with watch

gsettings set org.gnome.desktop.background picture-path

* Keyboard
- Caps lock as left CTRL
- left CTRL as compose key
- US and RU keyboards

* Sync org files
#+begin_src bash
  owncloudcmd -s -u user -p pw $HOME/NextCloud/ https://cloud.owncube.com/remote.php/webdav/
#+end_src

[[https://github.com/owncloud/client/issues/2002#issuecomment-98747743][cron script for owncloud]]

* Telegram
telega for emacs?

* ssh keys?

* Email
[[https://www.fsf.org/resources/webmail-systems][fsf advice]]

[[https://www.emacswiki.org/emacs/GnusGmail][gnus tutorial]]

i68scb+18z6fep0c@sharklasers.com
aadcg@sharklasers.com

setup posteo email

webmail fcup?

aagomes@protonmail.com
aagomes@pm.com

disroot

* Emacs keybindings outside Emacs
~/.gtkrc
#+begin_comment
gtk-key-theme-name = "Emacs"
#+end_comment

* Wifi
nmtui

* Dictionary
aspell

* Brightness
xrand -s 2560x1440
xrand --output <screen> --brightness 0.x / 1
