(specifications->manifest
 '("git"
   "stow"
   ;; emacs
   "emacs"
   ;; packages
   "emacs-guix"
   "emacs-org"
   "emacs-org-bullets"
   "emacs-use-package"
   "emacs-pdf-tools"
   "emacs-telega"
   "emacs-zenburn-theme"
   "emacs-ivy"
   "emacs-smex"
   "emacs-avy"
   "emacs-emms"
   "emacs-smartparens"
   ;; dictionaries
   "aspell"
   "aspell-dict-en"
   "aspell-dict-pt-pt"
   "aspell-dict-ru"
   ;; fonts
   "font-hack"
   "font-fira-code"
   ;; browser
   "icecat"
   "next"
   ;; wm
   ;; "sway"
   ;; "swaylock"
   ;; "grim"                               ; screenshot
   ;; "i3status"                           ; status bar
   ;; "dmenu"
   ;; media
   "mpv"
   ;; sync files
   "owncloud-client"
   ;; python
   "emacs-elpy"
   "emacs-ob-ipython"
   ;; "emacs-ein"
   "python"
   "python-autopep8"
   "python-black"
   "python-flake8"
   "python-ipython"
   "python-jedi"
   "python-pip"
   "python-rope"
   "python-virtualenv"
   "python-yapf"
   ;; texlive
   ;; transmission
))

;; (define %emacs
;;   (map specification->package
;;        '("emacs"
;;          ;; "emacs-zenburn-theme"
;;          ;; "emacs-moody"
;;          "emacs-minions"
;;          "emacs-hide-mode-line"
;;          "emacs-avy"
;;          ;; "emacs-elpy"
;;          "emacs-company-jedi"
;;          ;; "emacs-ein"
;;          "emacs-haskell-mode"
;;          "emacs-go-mode"
;;          ;; "emacs-company-go"
;;          "emacs-auctex"
;;          "emacs-magit"
;;          "emacs-diff-hl"
;;          ;; "emacs-gitignore-mode"
;;          "emacs-yaml-mode"
;;          "emacs-csv-mode"
;;          "emacs-gitlab-ci-mode"
;;          "emacs-dockerfile-mode"
;;          "emacs-projectile"
;;          "emacs-rainbow-delimiters"
;;          "emacs-org"
;;          "emacs-ob-ipython"
;;          ;; "emacs-ob-go"
;;          "emacs-htmlize"
;;          ;; "emacs-org-drill"
;;          ;; "emacs-org-drill-table"
;;          "emacs-cdlatex"
;;          ;; "emacs-org-pdfview"
;;          "emacs-org-tree-slide"
;;          "emacs-org-bullets"
;;          "emacs-guix"
;;          ;; "emacs-pretty-sha-path"
;;          "emacs-flycheck"
;;          ;; "emacs-flyspell"
;;          "emacs-pdf-tools"
;;          "emacs-smartparens"
;;          "emacs-expand-region"
;;          ;; "emacs-counsel"
;;          "emacs-smex"
;;          "emacs-company"
;;          ;; "emacs-speed-type"
;;          ;; "emacs-default-text-scale"
;;          "emacs-google-translate"
;;          "emacs-emms"
;;          "emacs-telega"
;;          "emacs-emojify"
;;          "emacs-wttrin"
;;          )))
